apiVersion: v1
kind: Service
metadata:
  name: {{ include "iometrics.fullname" . }}
  labels:
    {{- include "iometrics.labels" . | nindent 4 }}
    servicemonitor: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: metrics
  selector:
    {{- include "iometrics.selectorLabels" . | nindent 4 }}
